
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: src/main/resources/script/prod_log.log
    clean-history-on-start: false
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
      boot:
        autoconfigure:
          data:
            rest: INFO
            jpa: INFO
            orm: INFO

# Configuraci√≥n Eureka - Usa variables de entorno desde ConfigMap en Kubernetes
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-discovery.ecommerce-prod.svc.cluster.local:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:api-gateway.ecommerce-prod.svc.cluster.local}

